WebUi/Models/AxGroupViewModel.cs
using System.ComponentModel.DataAnnotations;
using Model.Entities;

namespace WebUi.Models
{
    public class AxGroupViewModel : BaseViewModel<AxGroup>
    {
        [Display(Name = "نام کاربر")]
        public int UserId { get; set; }
    }
}

WebUi/Controllers/AxGroupController.cs
using System.Linq;
using System.Web.Mvc;
using Framework;
using Framework.Entities;
using Framework.Resources;
using Framework.Services;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Model.Entities;
using WebUi.Filters;
using WebUi.Models;

namespace WebUi.Controllers
{
    public class AxGroupController : BaseController<AxGroup, BaseViewModel<AxGroup>>
    {
        // GET: AxGroup
        public AxGroupController(IBaseService<AxGroup> service) : base(service)
        {
            Service = service;
        }

        [AxAuthorize(AxOp.GroupList, true)]
        public ActionResult List()
        {
            return View();
        }

        [AxAuthorize(ParentAxOp = AxOp.GroupList, StateType = StateType.CheckParent)]
        public JsonResult GetGroupList([DataSourceRequest] DataSourceRequest request)
        {
            var groupList = Service.GetAll().OrderByDescending(x => x.Id).Select(x => new
            {
                x.Id,
                x.GroupName,
                x.Description,
                x.InsertDateTime,

            });
            return Json(groupList.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        [AxAuthorize(AxOp.GroupItem)]
        public ActionResult Item(int id = 0)
        {
            var viewModel = new AxGroupViewModel();
            var model = Service.Find(id);
            if (model != null)
            {
                viewModel.Entity = model;
            }
            return View(viewModel);
        }

        [AxAuthorize(AxOp.GroupInsert)]
        public override ActionResult Insert(BaseViewModel<AxGroup> item)
        {
            var entity = item.Entity;
            Service.Add(entity);
            return Json(new ApiResult { Type = ApiResultType.Success, Msg = Words.SuccessInsert,Id=entity.Id });
        }

        [AxAuthorize(AxOp.GroupUpdate)]
        public override ActionResult Update(BaseViewModel<AxGroup> item)
        {
            var entity = item.Entity;
            Service.Update(entity);
            return Json(new ApiResult { Type = ApiResultType.Success, Msg = Words.SuccessEdit });
        }

        [AxAuthorize(AxOp.GroupDelete)]
        public override ActionResult Delete(int id)
        {
            return base.Delete(id);
        }
    }
}

WebUi/Controllers/UserGroupController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Framework;
using Framework.Entities;
using Framework.Resources;
using Framework.Services;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Model.Entities;
using WebUi.Filters;
using WebUi.Models;

namespace WebUi.Controllers
{
    public class UserGroupController : BaseController<UserGroup, BaseViewModel<UserGroup>>
    {
        // GET: UserGroup
        private readonly IBaseService<User> _userService;
        private readonly IBaseService<User> _personService;
        public UserGroupController(IBaseService<UserGroup> service, IBaseService<User> userService, IBaseService<Person> personService, IBaseService<User> personService1) : base(service)
        {
            _userService = userService;
            _personService = personService1;
            Service = service;
        }

        [AxAuthorize(AxOp.UserGroupList)]
        public ActionResult List()
        {
            return View();
        }

        [AxAuthorize(ParentAxOp = AxOp.UserGroupList, StateType = StateType.CheckParent)]
        public ActionResult GetList([DataSourceRequest]DataSourceRequest request, int? groupId)
        {
            var data = Service.GetAll(x => x.GroupId == groupId);
            var userData = new List<UserGroupViewModel>();
            foreach (UserGroup userGroup in data)
            {
                var user = _userService.GetAll(x => x.Id == userGroup.UserId).Include(x => x.Person).FirstOrDefault();
                if (user != null)
                    userData.Add(new UserGroupViewModel
                    {
                        Id = userGroup.Id,
                        UserName = user.UserName,
                        FullName = user.Person.FullName,
                        PersonalId = user.Person.PersonalId,
                    });
            }

            return Json(userData.ToList().ToDataSourceResult(request));
        }

        [AxAuthorize(AxOp.UserGroupInsert)]
        [HttpPost]
        public ActionResult InsertUserToGroup(int groupId, int? userId)
        {
            if (userId == null)
            {
                return Json(new ApiResult { Type = ApiResultType.Error, Msg = "لطفا کاربر مورد نظر را انتخاب نمایید" });
            }
            var row = Service.GetAll(x => x.GroupId == groupId && x.UserId == userId).Any();
            if (row)
            {
                return Json(new ApiResult { Type = ApiResultType.Error, Msg = "شخص مورد نظر قبلا در گروه عضو شده است" });
            }
            var userGroup = new UserGroup { GroupId = groupId, UserId = (int)userId };
            Service.Add(userGroup);
            return Json(new ApiResult { Type = ApiResultType.Success, Msg = Words.SuccessInsert });
        }

        [AxAuthorize(AxOp.UserGroupDelete)]
        [HttpPost]
        public ActionResult DeleteUserGroup(int id)
        {
            Service.Delete(id);
            return Json(new ApiResult { Type = ApiResultType.Success, Msg = Words.SuccessDelete });
        }
    }
}

WebUi/Views/AxGroup/Item.cshtml
@{
    ViewBag.Title = "Item";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using WebUi.AxKendo;
@model WebUi.Models.AxGroupViewModel

<script>
        $(document).ready(function() {
            if (@Model.Entity.Id != 0) {
                $("#usersDiv").show();
            } else {

                $("#usersDiv").hide();
            }
        });
        function InsertUserToGroup() {
            var userId = $("#UserId").val();
            debugger;
            var url = '@Url.Action("InsertUserToGroup", "UserGroup", new { systemKey = "Basic", groupId = Model.Entity.Id})' + '&userId=' + userId;
            Save(url, null, function () {
                RefreshGrid("UserGroupListGrid");
            });
    }
        function SaveItem() {
            var json = window.$("#AxGroupItemForm").serializeArray();
            var url;

            if (window.$("#Entity_Id").val() == 0) {

                url = '@Url.Action("Insert", "AxGroup", new {SystemKey = "Basic"})';
            } else {
                url = '@Url.Action("Update", "AxGroup", new {SystemKey = "Basic"})';
            }

            Save(url,
                json,
                function(result) {
                    var url = '@Url.Action("Item", "AxGroup", new {SystemKey = "Basic"})';
                    if ($("#Entity_Id").val() == 0) {
                        url = url + '/' + result.Id;
                    }
                    window.location.href = url;
                });
        }

        function Back() {
            var url = '@Url.Action("List")';
            ChangeUrl(url);
        }



</script>

<h2>گروه</h2>

<div class="x_panel">
    <div class="x_content">
        <br>
        <form id="AxGroupItemForm" class="form-group" data-parsley-validate="">

            @Html.HiddenFor(x => x.Entity.Id)
            @Html.HiddenFor(x => x.Entity.RowVersion)
            <div class="form-group col-md-3  col-xs-12">

                <div class="col-md-2">
                    @Html.AxLabelFor(x => x.Entity.GroupName)

                </div>
                <div class="col-md-7">
                    @Html.Kendo().TextBoxFor(x => x.Entity.GroupName).HtmlAttributes(new { @class = "form-control col-md-12 col-xs-12 ax-input" })
                </div>
                <div class="col-md-1"></div>
            </div>
            <div class="form-group col-md-9  col-xs-12">

                <div class="col-md-1">
                    @Html.AxLabelFor(x => x.Entity.Description)

                </div>
                <div class="col-md-10">
                    @Html.Kendo().TextBoxFor(x => x.Entity.Description).HtmlAttributes(new { @class = "form-control col-md-12 col-xs-12 width-input" })
                </div>
                <div class="col-md-1"></div>
            </div>
           
            <div class="col-md-12" id="usersDiv" style="position:initial; margin-top: 30px">
                <fieldset>
                    <legend>لیست کاربران عضو گروه</legend>
                    @Html.Action("List", "UserGroup", new { systemKey = "Basic", groupId = Model.Entity.Id })

                </fieldset>
            </div>

            <div class="form-group col-md-12 col-sm-6 col-xs-12 ax-container ">
                <div class="col-md-12 col-sm-6 col-xs-12 ">
                    <button type="button" class="btn btn-primary" onclick="Back()">بازگشت</button>
                    <button type="button" class="btn btn-success" onclick="SaveItem()">ذخیره</button>
                </div>
            </div>
        </form>
    </div>
</div>

WebUi/Views/AxGroup/List.cshtml
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script>

    function onNew() {

        ChangeUrl('@Url.Action("Item")');
    }

    function onEdit() {
        var selectedItem = GetSelectedGridRow("GroupListGrid");
        if (selectedItem) {
            var url = '@Url.Action("Item")';
            window.location.href = url + "/" + selectedItem.Id;
        }
    }

    function onDelete() {
        var selectedItem = GetSelectedGridRow("GroupListGrid");
        if (selectedItem) {
            var url = '@Url.Action("Delete", "AxGroup")?id=' + selectedItem.Id;
            ConfirmAlert(function() {
                Delete(url, function() {
                    RefreshGrid("GroupListGrid");
                });
            },null);
        }
    }

    $(document).ready(function() {
        $("#GroupListGrid").on("dblclick" , "tbody>tr", function (e) {onEdit()});
    });

</script>
<h2>لیست گروه ها</h2>

@(Html.Kendo().ToolBar()
    .Name("toolbar")
    .Items(items =>
    {
        items.Add().Type(CommandType.Button).Text("ثبت جدید").Click("onNew");
        items.Add().Type(CommandType.Button).Text("ویرایش").Click("onEdit");
        items.Add().Type(CommandType.Button).Text("حذف").Click("onDelete");
    }))

@(Html.AxGrid<AxGroup>("GroupListGrid", "AxGroup", "GetGroupList")
    .Columns(columns =>
    {
        columns.Bound(c => c.Id).Hidden();
        columns.Bound(c => c.GroupName).Width(300);
        columns.Bound(c => c.Description);
        columns.PersianDateTimeColumn(c => c.InsertDateTime).Width(200);
    })
    .Groupable(x => x.Enabled(false))
    .DataSource(dataSource => dataSource
        .Ajax()
    ))