WebUi/Models/PersonViewModel.cs
using System;
using Model.Entities;

namespace WebUi.Models
{
    public class PersonViewModel : BaseViewModel<Person>
    {
        public string FullName
        {
            get
            {
                return Entity.FirstName + " " + Entity.LastName;
            }
            set { }
        }
        public int PersonPictureId { get; set; }
        public Guid ImageId { get; set; }
        public byte[] Image { get; set; }
        public string SystemName
        {
            get
            {
                return "General";
            }
        }
        public string Birthday { get; set; }
    }
}

WebUi/Controllers/AddressController.cs
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Framework;
using Framework.Entities;
using Framework.Services;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Model.Entities;
using WebUi.Filters;
using WebUi.Models;

namespace WebUi.Controllers
{
    public class AddressController : BaseController<Address, AddressViewModel>
    {
        public AddressController(IBaseService<Address> service) : base(service)
        {
            Service = service;
        }

        // GET: Address

        [AxAuthorize(AxOp.AddressItem)]
        public ActionResult Item(int personId = 0, int id = 0)
        {
            AddressViewModel viewModel = new AddressViewModel();
            var model = Service.Find(id);
            if (model != null)
                viewModel.Entity = model;
            viewModel.Entity.PersonId = personId;
            return View(viewModel);
        }

        [AxAuthorize(AxOp.AddressList)]
        public ActionResult List(int personId)
        {
            ViewBag.PersonId = personId;
            return View(personId);
        }

        [AxAuthorize(ParentAxOp = AxOp.AddressList, StateType = StateType.CheckParent)]
        public ActionResult GetList([DataSourceRequest]DataSourceRequest request, int? personId)
        {
            var data = Service.GetAll(x => x.PersonId == personId).Include(x => x.GeoPos);
            return Json(data.Select(x => new
            {
                Entity = new
                {
                    x.Id,
                    x.Mobile,
                    x.Email,
                    x.Telephone,
                    x.PostalCode,
                    x.Fax,
                    x.IsMainAddress,
                    x.PostalBox,
                    x.AddressContent
                },
                GeoPosTitle = x.GeoPos.Title,
                x.InsertDateTime
            }).ToList().ToDataSourceResult(request));
        }

        [AxAuthorize(AxOp.AddressInsert)]
        public override ActionResult Insert(AddressViewModel item)
        {
            return base.Insert(item);
        }

        [AxAuthorize(AxOp.AddressUpdate)]
        public override ActionResult Update(AddressViewModel item)
        {
            return base.Update(item);
        }
    }
}

WebUi/Controllers/ImageController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Framework.Entities;
using Framework.Services;
using Framework.Tools;
using Model.Entities;
using Model.Enum;
using WebUi.Filters;
using WebUi.Models;

namespace WebUi.Controllers
{
    public class ImageController : BaseController<File, FileViewModel>
    {
        public ImageController(IBaseService<File> service) : base(service)
        {
            Service = service;
        }

        [AxAuthorize(AxOp.PersonImageShow)]
        public ActionResult Show(int id, string guid)
        {
            if (id != 0)
            {
                var imageData = Service.Find(id);
                var mimeType = MimeMapping.GetMimeMapping(imageData.FileName);
                if (imageData.FileContent != null && imageData.FileContent.Length > 0)
                {
                    return File(imageData.FileContent, mimeType, imageData.FileName);
                }
            }

            if (!string.IsNullOrWhiteSpace(guid))
            {
                var pic = FileCache.FileCacheList.FirstOrDefault(x => x.Id.ToString() == guid);
                if (pic?.FileContent != null && pic.FileContent.Length > 0)
                {
                    var mimeType = MimeMapping.GetMimeMapping(pic.FileName);
                    return File(pic.FileContent, mimeType, pic.FileName);
                }
            }
            return null;
        }

        [AxAuthorize(AxOp.PersonImageDelete)]
        [HttpGet]
        public ActionResult DeletePic(int id)
        {
            var image = Service.GetAll(x => x.PersonId == id && x.FileType == FileEnum.PersonPicture).SingleOrDefault();
            if (image != null)
            {
                Service.Delete(image);
            }
            return null;
        }

        [AxAuthorize(AxOp.PersonImageInsert)]
        public ActionResult AddPictureInCache(HttpPostedFileBase image)
        {
            if (image == null) return null;
            var data = StreamHelper.ReadToEnd(image.InputStream);
            var title = System.IO.Path.GetFileName(image.FileName);

            var newFile = new UploadFile
            {
                Id = Guid.NewGuid(),
                FileName = title,
                FileType = FileEnum.PersonPicture.GetDisplayName(),
                FileContent = data,
                Size = image.ContentLength,
                InsertTime = DateTime.Now
            };
            FileCache.Add(newFile);
            return Json(new ApiResult<UploadFile>
            {
                Type = ApiResultType.Success,
                Temp = newFile.Id.ToString()
            });
        }
    }
}

WebUi/Controllers/PersonController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Framework;
using Framework.Entities;
using Framework.Resources;
using Framework.Services;
using Framework.Tools;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Model.Entities;
using Model.Enum;
using WebUi.Filters;
using WebUi.Models;

namespace WebUi.Controllers
{
    public class PersonController : BaseController<Person, PersonViewModel>
    {
        private readonly IBaseService<File> _fileService;

        public PersonController(IBaseService<Person> personService, IBaseService<File> fileService) : base(personService)
        {
            Service = personService;
            _fileService = fileService;
        }

        [AxAuthorize(AxOp.PersonList, true)]
        public ActionResult List()
        {
            return View();
        }

        [AxAuthorize(ParentAxOp = AxOp.PersonList, StateType = StateType.CheckParent)]
        public JsonResult GetPersonList([DataSourceRequest] DataSourceRequest request)
        {
            var personList = Service.GetAll().OrderByDescending(x => x.Id).Select(x => new
            {
                x.Id,
                x.NationalCode,
                FullName = x.FirstName + " " + x.LastName,
                x.IdentityNumber,
                x.FatherName,
                x.Sex,
                x.InsertDateTime
            });
            return Json(personList.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        [AxAuthorize(AxOp.PersonItem)]
        public ActionResult Item(int id = 0)
        {
            PersonViewModel viewModel = new PersonViewModel();
            var model = Service.Find(id);
            if (model != null)
            {
                viewModel.Entity = model;
                viewModel.Birthday = viewModel.Entity.Birthday?.ToPerDateTimeString("yyyy/MM/dd");
                var img = _fileService.GetAll(x => x.PersonId == id && x.FileType == FileEnum.PersonPicture).SingleOrDefault();
                if (img != null)
                    viewModel.PersonPictureId = img.Id;
            }
            return View(viewModel);
        }

        [AxAuthorize(AxOp.PersonInsert)]
        public override ActionResult Insert(PersonViewModel item)
        {
            var entity = item.Entity;
            entity.Birthday = item.Birthday.GetMiladiDate();
            Service.Add(entity);
            var personId = entity.Id;
            var file = FileCache.FileCacheList?.FirstOrDefault(x => x.Id == item.ImageId);
            if (file != null)
            {
                var newFile = new File
                {
                    Title = file.FileName,
                    FileName = file.FileName,
                    FileType = FileEnum.PersonPicture,
                    FileContent = file.FileContent,
                    Size = file.FileContent.Length,
                    PersonId = personId
                };
                _fileService.Add(newFile);
                FileCache.FileCacheList.Remove(file);
            }

            return Json(new ApiResult
            {
                Id = personId
            });
        }

        [AxAuthorize(AxOp.PersonUpdate)]
        public override ActionResult Update(PersonViewModel item)
        {
            var entity = item.Entity;
            entity.Birthday = item.Birthday.GetMiladiDate();
            Service.Update(entity);
            var file = FileCache.FileCacheList?.FirstOrDefault(x => x.Id == item.ImageId);
            if (file == null)
                return Json(new ApiResult { Type = ApiResultType.Success, Msg = Words.SuccessEdit });
            var oldFile = _fileService.GetAll(x => x.PersonId == item.Entity.Id).FirstOrDefault();
            if (oldFile != null)
            {
                _fileService.Delete(oldFile);
            }
            var newFile = new File
            {
                Title = file.FileName,
                FileName = file.FileName,
                FileType = FileEnum.PersonPicture,
                FileContent = file.FileContent,
                Size = file.FileContent.Length,
                PersonId = entity.Id
            };
            _fileService.Add(newFile);
            FileCache.FileCacheList.Remove(file);
            return Json(new ApiResult { Type = ApiResultType.Success, Msg = Words.SuccessEdit });
        }

        [AxAuthorize(AxOp.PersonDelete)]
        public override ActionResult Delete(int id)
        {
            var img = _fileService.GetAll(x => x.PersonId == id && x.FileType == FileEnum.PersonPicture).FirstOrDefault();
            if (img != null)
                _fileService.Delete(img.Id);
            return base.Delete(id);
        }

    }
}

WebUi/Views/Person/Item.cshtml
@using Framework.Tools
@using Model.Enum
@using WebUi.AxKendo;
@model WebUi.Models.PersonViewModel
@{
    ViewBag.Title = "ثبت جدید شخص";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script>

    $(document).ready(function() {
        if (@Model.Entity.Id != 0) {
            $("#addressDiv").show();
        }
        else {

            $("#addressDiv").hide();
        }
        if (@Model.PersonPictureId != 0) {
            $("#DeletePic").show();
        }
        else {
            $("#DeletePic").hide();
        }
    });

    function SavePersonItem() {
        var json = window.$("#PersonItemForm").serializeArray();
        var url;

        if ($("#Entity_Id").val() == 0) {

            url = '@Url.Action("Insert", "Person",new {SystemKey="Basic"})';
        }
        else
        {
            url = '@Url.Action("Update", "Person",new {SystemKey="Basic"})';
        }

        Save(url,
            json,
            function (result) {
                var url = '@Url.Action("Item", "Person", new {SystemKey = "Basic"})' ;
                if ($("#Entity_Id").val() == 0) {
                    url = url + '/' + result.Id;
                }
            window.location.href = url;
        });
    }

    function Back() {
        var url = '@Url.Action("List")';
        ChangeUrl(url);
    }

    function afterUpload(e) {
        $("#ImageId").val(e.response.Temp);
        var d = new Date();
        $("#person-img").attr('src', '/Basic/Image/Show?id=0&guid=' + e.response.Temp + '&rand=' + d.getTime());
        $("#DeletePic").css('display', 'block');

    }

    function onError(e) {
        var err = $.parseJSON(e.XMLHttpRequest.responseText);
        alert(err.Message);
        $.map(e.files,
            function(file) {
                alert("Could not upload " + file.name);
            });
    }

    function OnPicDelete() {
        $.ajax({
            url:  '@Url.Action("DeletePic","Image")'+ "?id=" + @Model.Id ,
            type: "Get",
            success: function (result) {
                $("#ImageId").val(null);
                $("#person-img").attr('src', '');
                $("#DeletePic").css('display', 'none');
            }
        });
    }

</script>

<h2>فرم شخص</h2>

<div class="x_panel">
    <div class="x_content">
        <br>
        <form id="PersonItemForm" class="form-group" data-parsley-validate="">

            @Html.HiddenFor(x => x.Entity.Id)
            @Html.HiddenFor(x => x.Entity.RowVersion)
            @Html.HiddenFor(x => x.ImageId)
            <div class="row" style="padding: 15px;">
                <div class="col-md-10 ">
                    <div class="form-group col-md-4  col-xs-12">
                        <div class="col-md-4">
                            @Html.AxLabelFor(x => x.Entity.FirstName)
                        </div>
                        <div class="col-md-7">
                            @Html.Kendo().TextBoxFor(x => x.Entity.FirstName).HtmlAttributes(new { @class = "form-control col-md-12 col-xs-12 ax-input" })
                        </div>
                        <div class="col-md-1"></div>
                    </div>
                    <div class="form-group col-md-4  col-xs-12">

                        <div class="col-md-4">
                            @Html.AxLabelFor(x => x.Entity.LastName)

                        </div>
                        <div class="col-md-7">
                            @Html.Kendo().TextBoxFor(x => x.Entity.LastName).HtmlAttributes(new { @class = "form-control col-md-12 col-xs-12 ax-input" })
                        </div>
                        <div class="col-md-1"></div>
                    </div>
                    <div class="form-group col-md-4  col-xs-12">

                        <div class="col-md-4">
                            @Html.AxLabelFor(x => x.Entity.FatherName)

                        </div>
                        <div class="col-md-7">
                            @Html.Kendo().TextBoxFor(x => x.Entity.FatherName).HtmlAttributes(new { @class = "form-control col-md-12 col-xs-12 ax-input" })
                        </div>
                        <div class="col-md-1"></div>
                    </div>
                    <div class="form-group col-md-4  col-xs-12">
                        <div class="col-md-4">
                            @Html.AxLabelFor(x => x.Entity.Sex)
                        </div>
                        <div class="col-md-7">

                            @(Html.Kendo().DropDownListFor(x => x.Entity.Sex)
                                .HtmlAttributes(new { @class = " txt-width form-control col-md-4 col-xs-12 ax-input" })
                                .Value(@Model.Entity.Sex.ToString())
                                .BindTo(from SexEnum r in Enum.GetValues(typeof(SexEnum)) select new { Id = (int)r, Name = r.GetDisplayName() })
                                .DataTextField("Name").DataValueField("Id")
                                .OptionLabel("انتخاب کنید"))
                        </div>
                    </div>
                    <div class="form-group col-md-4  col-xs-12">

                        <div class="col-md-4">
                            @Html.AxLabelFor(x => x.Entity.LatinName)

                        </div>
                        <div class="col-md-7">
                            @Html.Kendo().TextBoxFor(x => x.Entity.LatinName).HtmlAttributes(new { @class = "form-control col-md-12 col-xs-12 ax-input" })
                        </div>
                        <div class="col-md-1"></div>
                    </div>
                    <div class="form-group col-md-4  col-xs-12">

                        <div class="col-md-4">
                            @Html.AxLabelFor(x => x.Entity.LatinLastName)

                        </div>
                        <div class="col-md-7">
                            @Html.Kendo().TextBoxFor(x => x.Entity.LatinLastName).HtmlAttributes(new { @class = "form-control col-md-12 col-xs-12 ax-input" })
                        </div>
                        <div class="col-md-1"></div>
                    </div>
                    <div class="form-group col-md-4  col-xs-12">
                        <div class="col-md-4">
                            @Html.AxLabelFor(x => x.Entity.Birthday)
                        </div>
                        <div class="col-md-7">
                            <div class="controls">
                                @(Html.Kendo().MaskedTextBoxFor(x => x.Birthday)
                                    .Mask("0000/00/00")
                                    .HtmlAttributes(new { @class = "form-control col-md-12 col-xs-12 ax-input", style = "text-align:center;direction:ltr" }))
                            </div>
                        </div>
                        <div class="col-md-1"></div>
                    </div>
                    <div class="form-group col-md-4 col-sm-3 col-xs-12">
                        <div class="col-md-4">
                            @Html.AxLabelFor(x => x.Entity.NationalCode)

                        </div>
                        <div class="col-md-7">
                            @Html.Kendo().TextBoxFor(x => x.Entity.NationalCode).HtmlAttributes(new { @class = "form-control ax-input" })
                        </div>
                        <div class="col-md-1"></div>
                    </div>
                    <div class="form-group col-md-4 col-sm-3 col-xs-12">
                        <div class="col-md-4">
                            @Html.AxLabelFor(x => x.Entity.IdentityNumber)
                        </div>
                        <div class="col-md-7">
                            @Html.Kendo().TextBoxFor(x => x.Entity.IdentityNumber).HtmlAttributes(new { @class = "form-control ax-input" })
                        </div>
                        <div class="col-md-1"></div>
                    </div>
                    <div class="form-group col-md-4  col-xs-12">
                        <div class="col-md-4" style="margin-right: 3px;">
                            @Html.AxLabelFor(x => x.Entity.IdentitySerial)
                        </div>
                        <div class="col-md-7">
                            @Html.Kendo().TextBoxFor(x => x.Entity.IdentitySerial).HtmlAttributes(new { @class = "form-control col-md-12 col-xs-12 ax-input" })
                        </div>
                        <div class="col-md-1"></div>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group col-md-12 col-sm-12 col-xs-12">
                        <div style="padding-right:40px;padding-bottom:10px; margin: 0;" class="input-group">
                            @{
                                var rand = new Random();
                                var imgUrl = Url.Action("Show", "Image") + "?id=" + @Model.PersonPictureId + "&rand=" + rand.Next(5000);
                            }
                            <img id="person-img" style="width: initial; max-width: 100px; max-height: 100px;min-width: 90px; min-height: 90px;" alt="بدون تصویر" onerror="this.src='/Content/Images/no-image.jpg';" src='@imgUrl' />
                            <br />
                            <a class="txtLink" id="DeletePic" onclick="OnPicDelete() ">حذف تصویر</a>
                        </div>
                        <div style="float: right;padding-right: 20px" class="input-group ">
                            @(Html.Kendo().Upload()
                                .Name("Image").ShowFileList(false)
                                .Events(evt => evt.Error("onError").Success("afterUpload"))
                                .Async(a => a
                                    .Save("AddPictureInCache", "Image", new { Model.Image })
                                    .AutoUpload(true)).Messages(x => x.Cancel("لغو").Retry("دوباره").Select("انتخاب").StatusUploading("در حال بارگذاری").HeaderStatusUploaded("موفق").StatusFailed("خطا داد").HeaderStatusUploading("در حال بارگذاری"))
                                .Multiple(false)
                            )
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12" id="addressDiv" style="position:initial;">
                <fieldset>
                    <legend>آدرس ها</legend>
                    @Html.Action("List", "Address", new { systemKey = "Basic", personId = Model.Entity.Id })

                </fieldset>
            </div>
            <div class="form-group col-md-12 col-sm-6 col-xs-12 ax-container ">
                <div class="col-md-12 col-sm-6 col-xs-12 ">
                    <button type="button" class="btn btn-primary" onclick="Back()">بازگشت</button>
                    <button type="button" class="btn btn-success" onclick="SavePersonItem()">ذخیره</button>
                </div>
            </div>
        </form>
    </div>
</div>

WebUi/Views/Person/List.cshtml
@using Model.Entities
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script>

    function onNew() {

        ChangeUrl('@Url.Action("Item")');


    }

    function onEdit() {
        var selectedItem = GetSelectedGridRow("PersonListGrid");
        if (selectedItem) {
            var url = '@Url.Action("Item")';
            window.location.href = url + "/" + selectedItem.Id;
        }
    }

    function onDelete() {
        var selectedItem = GetSelectedGridRow("PersonListGrid");
        if (selectedItem) {
            var url = '@Url.Action("Delete", "Person")?id=' + selectedItem.Id;
            ConfirmAlert(function() {
                Delete(url, function() {
                    RefreshGrid("PersonListGrid");
                });
            },null);
        }
    }

    $(document).ready(function() {
        $("#PersonListGrid").on("dblclick", "tbody>tr", function(e) { onEdit() });
    });

</script>
<h2>لیست اشخاص</h2>

@(Html.Kendo().ToolBar()
    .Name("toolbar")
    .Items(items =>
    {
        items.Add().Type(CommandType.Button).Text("ثبت جدید").Click("onNew");
        items.Add().Type(CommandType.Button).Text("ویرایش").Click("onEdit");
        items.Add().Type(CommandType.Button).Text("حذف").Click("onDelete");
    }))

@(Html.AxGrid<Person>("PersonListGrid", "Person", "GetPersonList")
    .Columns(columns =>
    {
        columns.Bound(c => c.Id).Hidden();
        columns.StringColumn(c => c.FullName);
        columns.StringColumn(c => c.FatherName);
        columns.NumericColumn(c => c.IdentityNumber);
        columns.NumericColumn(c => c.NationalCode).Title("کد ملی");
        columns.BooleanColumn(c => c.Sex, "مرد", "زن");
        columns.PersianDateTimeColumn(c => c.InsertDateTime).Width(200);
    })
    .Groupable(x => x.Enabled(false))
    .DataSource(dataSource => dataSource
        .Ajax()
    ))